### ISSUE TITLE
Support markdown or html in article_first

### ISSUE THREAD

**Issue by fno2010** [snlab-freedom/hugo-theme-cooler#8]
`article_first` partial reads `[params.article_first]` from `config.toml` to render the introduction. Current `[params.article_first]` is like the following:

``` toml
[params.article_first]
    title = "example title"
    body = [
    "This is paragraph 1.",
    "This is paragraph 2."
    ]
    rss_show = true
```

But it cannot support markdown or html syntax in `title` and `body` variables. We may want to make the introduction look like more readable, rather than only plain text.
